### ISSUE TITLE
Index-out-of bounds error in TGeant3TGeo::FinishGeometry()

### ISSUE THREAD

**Issue by sawenzel** [vmc-project/geant3#2] opened 2017-05-23 14:00 UTC
I observed error-out-of bounds errors reported by `ROOT::TArrayI` in the following code snipped of `FinishGeometry():`

```C++
// if material is already used define a new Geant3 material                                                             
// (do not reset TGeoMaterial index)                                                                                    
if (usedMaterials[nmat] >0 )
  nmat = ImportMaterial(med->GetMaterial());
usedMaterials[nmat] = 1;
```

I believe, one should add a check whether `nmat `is a good index for `usedMaterials` and only access `useMaterials` in those cases.

**Comment by sawenzel** [comment] 2017-05-23 14:00
@ihrivnac : Can you please take a look?

**Comment by shahor02** [comment] 2017-05-23 15:18
I think it is a bug in TGeant3TGeo: the internal material ID kmat returned in TGeant3TGeo::Material by the G3Material(kmat, name, a, z, dens, radl, absl, fbuf, nwbuf) seems to follow fortran convention (starts from 1), so the maxNofMaterials in TGeant3TGeo::FinishGeometry() should be defined as incremented by 1: Int_t maxNofMaterials = nofMaterials + nofMedia+1

**Comment by ihrivnac** [comment] 2017-05-24 09:36
The problem here is that  materials are defined via VMC interface:
gMC->Material(imat, uniquename.Data(), a, z, dens * mDensityFactor, radl, absl, buf, nwbuf);
etc.
and then, we call via FairRoot MCApplication 
gMC->SetRootGeometry(true);

This will invoke importing materials in Geant3 on the top of existing materials, and so the materials numbering in Root (via SetUniqueID) starts from 29 (id we run run_sim_tpc.C), and the array gets out of bound.

Note that in AliRoot, when we build geometry from the code (and create materials via VMC interface), we do not call SetRootGeometry(), while in FairRoot, they build materials via TGeo.

I think the best solution to this would be to change the functions for  creating materials  in
AliceO2::Base::Detector 
and replace the calls to gMC with equivalent calls to gGeoManager.
This will create only Root materials and so all materials will be imported to Geant3 in FinishGeometry.

**Comment by sawenzel** [comment] 2017-05-24 10:04
Thanks for this info. We can fix this in user code.

However, I believe what you are describing is a clear error condition (or a misuse) which should preferably be caught in Geant3 with a clear error message.

**Comment by ihrivnac** [comment] 2017-05-24 10:08
Yes, I am just looking in a suitable protection ...

**Comment by ihrivnac** [comment] 2017-05-24 13:09
The problem is now fixed and the fix is included in the v2-4.
The temporary array size is increased to take into account the materials already defined in Geant3 and also the numbering starting from 1  as pointed by Ruben and a warning is issued aboute the presence of G3 materials while asking Import from ROOT.
In general this configuration can still work fine (as we see in O2 when running ITS), but the import of materials from ROOT is redundant.

**Closed as completed** 2017-05-24 13:09 UTC
